### ISSUE TITLE
keyboard_key() does not work

### ISSUE THREAD

**Issue by LittleWhite-tb** [Wolf2789/ROCCAT-SuoraFX-Effects-Animator#2]
Hello,

 I have tried the code that we can see in the screenshot and it does not work. I have tried some simple
```
keyboard_key(0,0,255,0,0)
keyboard_update()
```
But it does not do anything.

There is two effect while running the code :
- sometimes, I got the static lighting that I have set in the ROCCAT Swarm tool
- sometimes, it does not do anything, just keeps the previous effect that I have set

**Comment by Wolf2789** [comment]
Yes I know about that, I mentioned somewhere that it's not fully working and I'm working on it. I can't figure out why it's not working, because in plain cpp console application I can do everything and here it seems that interrupt data isn't sent. Currently I'm doing what I can to fix this, but I have other things to do and it's not easy to reconcile everything with each other.

**Comment by LittleWhite-tb** [comment]
I did not want to blame you. At some point, I thought it could be a firmware problem (e.g. not using the same firmware as you). Since I don't know Vala, I am not sure if I can help you on this one.

**Comment by Wolf2789** [comment]
Fixed. Check if it's working for you :)

**Comment by LittleWhite-tb** [comment]
Yes, everything looks fine. Well done !
