### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by LittleWhite-tb** [Wolf2789/ROCCAT-SuoraFX-Effects-Animator#3]
[Stefan Achatz](https://sourceforge.net/p/roccat/support-requests/73/) pointed me your [discussion](https://www.reddit.com/r/Roccat/comments/64itto/suorafx_reverse_engineering/).  So, like you, I am a Linux user and I have the SuoraFX.
You already did a wonderful work !

It would be cool if you could explain that you have found (something [like this](http://roccat.sourceforge.net/) for the SuoraFX) and, how you did configure Wireshark.

**Comment by Wolf2789** [comment]
Installation process:
1. Install VirtualBox on my Linux machine, and create new virtual machine with any version of Windows that supports Roccat Swarm and install Swarm there, let it update and download SuoraFX module. Of course for this step you need to know, that everytime you launch VM you need to connect also USB device with VirtualBox menu, because when SuoraFX isn't connected directly to the VM, Swarm just can't recognize it.
2. Install Wireshark.
3. Determine if you can use `modprobe usbmon`

Debugging process:
1. Open terminal and type:
a) `sudo modprobe usbmon` (if successful, then you should see no output)
b) `lsusb` - determine where is connected SuoraFX (Bus ID and Interface ID):
```
$ lsusb
Bus 001 Device 002: ID 8087:8000 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 004: ID 04f2:b40a Chicony Electronics Co., Ltd 
Bus 002 Device 003: ID 1e7d:2cef ROCCAT 
Bus 002 Device 002: ID 1e7d:3246 ROCCAT     <---- THIS IS SUORAFX <1E7D:3246> (0x1E7D is Roccat's VendorID and 0x3246 is SuoraFX ProductID)
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

2. Open Wireshark, and determine which usbmon you should use then open it (I don't know how, but I determined it by simply selecting all of them and searching if packets from SuoraFX exists there [just tried pressing keyboard keys and see what happens])

3. In Wireshark apply a display filter: `usb.bus_id==2 and usb.device_address==2 && usb.src==host` (bus_id and device_address values are determined by lsusb output)
4. Now you should be able to capture packets that are sent to device so open Swarm in VM and try to set any preset and if it's succesfully captured, then stop capturing in wireshark and examine data you've just captured.

**Comment by LittleWhite-tb** [comment]
Super ! Maybe you should place these info in the GIthub wiki of your project ?

**Comment by Wolf2789** [comment]
I think that's actually good idea :)
